port = 4000
lease = "0"
socket = ""
enable-table-lock = true

max-index-length = 12288

# When create table, split a separated region for it. It is recommended to
# turn off this option if there will be a large number of tables created.
split-table = false
new_collations_enabled_on_first_bootstrap = true

[log]
level = "error"

[status]
status-port = 9081

[performance]
stats-lease = "0"

# experimental section controls the features that are still experimental: their semantics,
# interfaces are subject to change, using these features in the production environment is not recommended.
[experimental]
allow-expression-index = true
